services:
  zocr:
    image: helloz/zocr
    container_name: zocr
    ports:
      - "5080:5080"
    environment:
      - TOKEN=your_token_here
      - WORKERS=1
      - OCR_MODEL_VERSION=tiny
    restart: always
