services:
  zocr:
    image: helloz/zocr
    container_name: zocr
    ports:
      - "5080:5080"
    environment:
      - ZOCR_TOKEN=your_token_here
      - ZOCR_WORKERS=1
      - ZOCR_MODEL_VERSION=tiny
    restart: always
